on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.26.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@be3c94b385c4f180051c996d336f57a34c397495 # v3
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3

    - name: Run Revive Action by pulling pre-built image
      uses: docker://morphy/revive-action@sha256:1ec5904abc4d8b2cd5fbb2987fc79a227f21a4231d757cc9a09a9ee3ab3c328b # v2
      with:
        exclude: "./vendor/..."

    - name: Run go fmt
      run: go fmt ./...
      #run: diff -u <(echo -n) <(gofmt -d -s .)

    - name: Run go vet
      run: go vet ./...

    - name: Test
      run: sudo ./hack/test.sh

    - name: Send coverage
      uses: shogo82148/actions-goveralls@8781f5dd05b691c4dd042d5e859c11c73e0104fa # v1
      with:
        path-to-profile: coverage.out
        flag-name: Go-${{ matrix.go }}
        parallel: true

  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@8781f5dd05b691c4dd042d5e859c11c73e0104fa # v1
        with:
          parallel-finished: true
